# Generated by Django 4.1.6 on 2023-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=4000, verbose_name='Yanglik matni *'),
        ),
    ]
